# Central-only options; corne.conf still applies to both halves.
CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_BOOT=y
CONFIG_USB_HID_BOOT_PROTOCOL=y

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
